name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:20.10.16-dind
        options: --privileged

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin ghcr.io

    - name: Build and push Docker image
      run: |
        docker build . -t ghcr.io/bastien-mva/docker_image:latest
        docker push ghcr.io/bastien-mva/docker_image:latest
